networks:
  freemarket-network:
    driver: bridge

services:
  db:
    image: postgres:16.6
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - freemarket-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    restart: unless-stopped
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: vizarb/backend:latest
    command: >
      sh -c "python manage.py makemigrations --noinput &&
              python manage.py migrate --noinput &&
              python manage.py dbreset &&
              python manage.py seed &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Backend:/app
      - media_data:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./Backend/.env.backend.local
    depends_on:
      db:
        condition: service_healthy
    networks:
      - freemarket-network

  frontend:
    restart: unless-stopped
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    image: vizarb/frontend:latest
    command: sh -c "yarn install && yarn dev"
    volumes:
      - ./Frontend:/app:cached
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    env_file:
      - ./Frontend/.env.frontend.local
    depends_on:
      - backend
    networks:
      - freemarket-network

volumes:
  postgres_data:
  media_data:
  frontend_node_modules:
