# Generated by Django 5.1.4 on 2025-06-11 11:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_adding_enums_to_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOverview',
            fields=[
                ('cart_item_id', models.IntegerField()),
                ('cart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('owner', models.CharField(max_length=255)),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('total_quantity', models.PositiveIntegerField()),
                ('latest_price', models.BigIntegerField()),
                ('item_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cart_overview',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_cents', models.BigIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('seller', models.CharField(max_length=255)),
                ('categories', models.TextField()),
                ('category_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('search_vector', models.TextField()),
            ],
            options={
                'db_table': 'item_details',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ItemSearchView',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_cents', models.BigIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('seller', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=20)),
                ('categories', models.TextField()),
                ('category_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('service_duration', models.IntegerField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=255, null=True)),
                ('search_vector', models.TextField()),
            ],
            options={
                'db_table': 'item_search_view',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='MostActiveUsers',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('total_orders', models.IntegerField()),
                ('total_spent', models.BigIntegerField()),
            ],
            options={
                'db_table': 'most_active_users',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('customer', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('total_price_cents', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'order_details',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='OrderItemDetails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('price_cents', models.BigIntegerField()),
            ],
            options={
                'db_table': 'order_item_details',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_cents', models.BigIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('seller', models.CharField(max_length=255)),
                ('categories', models.TextField()),
                ('category_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('search_vector', models.TextField()),
            ],
            options={
                'db_table': 'product_details',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_cents', models.BigIntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('seller', models.CharField(max_length=255)),
                ('categories', models.TextField()),
                ('category_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None)),
                ('service_duration', models.IntegerField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=255, null=True)),
                ('search_vector', models.TextField()),
            ],
            options={
                'db_table': 'service_details',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='TopSellingProducts',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('total_sold', models.IntegerField()),
                ('total_revenue', models.BigIntegerField()),
            ],
            options={
                'db_table': 'top_selling_products',
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserOrderHistory',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('customer', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('total_price_cents', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('total_items', models.IntegerField()),
            ],
            options={
                'db_table': 'user_order_history',
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
