# Generated by Django 5.1.4 on 2025-06-17 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_cartoverview_itemdetails_itemsearchview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerapplication',
            name='bank_swift_code',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid SWIFT/BIC code (8 or 11 uppercase letters/numbers).', regex='^[A-Z]{6}[A-Z0-9]{2}([A-Z0-9]{3})?$')]),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='national_id',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='ID must be alphanumeric and 9–15 characters long.', regex='^[A-Za-z0-9]{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format '+999999999'. Up to 15 digits allowed.", regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='tax_id',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='ID must be alphanumeric and 9–15 characters long.', regex='^[A-Za-z0-9]{9,15}$')]),
        ),
    ]
