# Generated by Django 5.1.4 on 2025-07-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_sellerapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('Other', 'Other'), ('Consulting', 'Consulting'), ('Delivery', 'Delivery'), ('Setup', 'Setup'), ('Custom', 'Custom')], default='Other', max_length=50),
        ),
    ]
