name: Build & Push Docker Images

on:
  workflow_run:
    workflows: ["Auto Tag Commits"]
    types: [completed]

jobs:
  build_and_push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare .env
        run: echo "${{ secrets.DOTENV_FILE }}" > .env

      - name: Build & Push
        run: |
          # explicitly tell Compose where the file is
          docker compose -f ./docker-compose.yml --env-file .env build
          docker tag vizarb/backend:$TAG vizarb/backend:latest
          docker tag vizarb/frontend:$TAG vizarb/frontend:latest

          docker push vizarb/backend:$TAG
          docker push vizarb/backend:latest
          docker push vizarb/frontend:$TAG
          docker push vizarb/frontend:latest
