name: Test and Coverage

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  backend-tests:
    name: Django Backend CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend

    env:
      DJANGO_DEBUG: 'False'
      DJANGO_SECRET_KEY: 'test-secret-key'
      POSTGRES_HOST: localhost
      POSTGRES_PORT: '5432'
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('Backend/requirements.txt') }}

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Postgres
        run: until pg_isready -h "$POSTGRES_HOST" -p "$POSTGRES_PORT"; do sleep 1; done

      - name: Run Tests + Coverage
        run: |
          pytest \
            --cov=base \
            --cov-report=xml \
            --cov-report=term \
            --cov-fail-under=75 \
            tests/

      - name: Upload Coverage XML
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: Backend/coverage.xml
