name: Test Reports & Email

on:
  workflow_run:
    workflows: ["Test and Coverage"]
    types:
      - completed

jobs:
  report-and-email:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend

    steps:
      - uses: actions/checkout@v3

      - name: Restore Coverage Artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: Backend/

      - name: Generate HTML Coverage Report
        run: |
          pip install coverage
          coverage html

      - name: Zip HTML Report
        run: zip -r coverage-report.zip htmlcov

      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage
          path: Backend/coverage-report.zip

      - name: Email Pytest Report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: |
            [CI] Full Report for ${{ github.repository }} @ ${{ github.sha }}
          body: |
            The detailed HTML coverage report is attached.
          to:   ${{ secrets.SMTP_USERNAME }}
          from: ${{ secrets.SMTP_USERNAME }}
          secure: true
          attachments: Backend/coverage-report.zip
